# https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml

# loki config generation
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  compactor:
    retention_enabled: true
  limits_config:
    retention_period: 720h

# disable unnecessary deployments that comes with Loki Helm 3.0.0+
rbac:
  pspEnabled: false
monitoring:
  dashboards:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
test:
  enabled: false
metricsInstance:
  enabled: false
gateway:
  enabled: false